" colorscheme peachpuff
" colorscheme wildcharm
" colorscheme desert
" colorscheme slate
" colorscheme desert
colorscheme deserted

set number
set relativenumber
 set cursorline
set nowrap
set scrolloff=5
set sidescrolloff=8

set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent

set listchars=trail:*,leadmultispace:·\ \ \ ,tab:·\ ·
set list

tmap <ESC> <C-\><C-n>
nmap [q :cprevious<CR>
nmap ]q :cnext<CR>
nmap [b :bprevious<CR>
nmap ]b :bnext<CR>
nmap [B :bad 

set viminfo+=n~/.vim/viminfo
runtime ftplugin/man.vim
filetype plugin on

set laststatus=2
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
set incsearch		" Incremental search
set hlsearch
set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
