" colorscheme peachpuff
" colorscheme wildcharm
" colorscheme desert
" colorscheme slate
colorscheme deserted

set number
set relativenumber
set cursorline
set nowrap
set scrolloff=5
set sidescrolloff=8

set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent

set listchars=trail:*,leadmultispace:·\ \ \ ,tab:·\ ·
set list

set laststatus=2
set incsearch
set hlsearch
set autowrite
set wildmenu
set wildmode=longest:full,full
set wildoptions=

packadd! matchit

tmap <ESC> <C-\><C-n>
nmap ; :
vmap ; :
nmap [q :cprevious<CR>
nmap ]q :cnext<CR>
nmap [b :bprevious<CR>
nmap ]b :bnext<CR>

runtime ftplugin/man.vim
filetype plugin on

if filereadable("./Session.vim")
    source Session.vim
endif

if has('nvim')
    set viminfo+=n~/.vim/nviminfo
else
    set viminfo+=n~/.vim/viminfo
endif
